### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Chr1Z93** [Chr1Z93/Lost-Ruins-of-Arnak-TTS#2]
- add names for new cards
- add Luascript with victory point value for new cards
- implement new research tracks
- implement new sites
- implement new leaders
- special handling for new cards like Miner's Helmet
- update setup XML
- update setup scripting

**Comment by covertskippy55** [comment]
- [ ]     add names for new cards
- [ ]     add Luascript with victory point value for new cards
- [ ]     implement new research tracks
- [ ]     implement new sites
- [X]     implement new leaders
- [ ]     special handling for new cards like Miner's Helmet
- [X]     update setup XML
- [ ]     update setup scripting

**Comment by Chr1Z93** [comment]
We also need snap points for the new leader boards

**Comment by Chr1Z93** [comment]
Solo content needs double-checking (Rival probably misbehaves on new research tracks) and Campaign needs implementation.
